import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import backpack1 from '../public/images/backpack.jpg';
import backpack2 from '../public/images/another-bag.jpg';
import backpack3 from '../public/images/hiking-bag.jpg';;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome To Detour</h1>

        <div className={styles.grid}>
          
          <article className={`${styles.featureProduct} ${styles.product}`}>
            <div className={styles.featureImageWrapper}>
              <Image
                src={backpack1}
                alt="backpack"
                layout="fill"
              />
            </div>
            <div className={styles.information}>
              <header>
                <h2>Our Coolest Product</h2>
              </header>
              <div className={`${styles.entryContent} ${styles.featureContent}`}>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                </p>
              </div>
              <Link href="/">
                <a>Learn More</a>
              </Link>
            </div>
          </article>
          
          <article id={styles.secondProduct} className={`${styles.secondaryProduct} ${styles.product}`}>
            <div className={styles.secondaryProductImageWrapper}>
              <Image
                src={backpack2}
                alt="stylish backpack"
              />
            </div>
            <div className={styles.information}>
              <header>
                <h2>Another Cool Product</h2>
              </header>
              <div className={styles.entryContent}>
                <p>Vivamus at elementum mi, phasellus dignissim enim dolor</p>
              </div>
              <Link href="/">
                <a>Learn More</a>
              </Link>
            </div>
          </article>

          <article id={styles.thirdProduct} className={`${styles.secondaryProduct} ${styles.product}`}>
            <div className={styles.secondaryProductImageWrapper}>
              <Image
                src={backpack3}
                alt="functional backpack"
              />
            </div>
            <div className={styles.information}>
              <header>
                <h2>A Third Cool Product</h2>
              </header>
              <div className={styles.entryContent}>
                <p>Curabitur ultricies dolor vel libero.</p>
              </div>
              <Link href="/">
                <a>Learn More</a>
              </Link>
            </div>
          </article>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
